name: DevSecOps End to End Pipeline

on:
    push:
        branches: [main]

jobs:
    # CI (Code  Integration with Secrutiy Scanning)
    Code-Quality:
        uses: ./.github/workflows/code-quality.yml
    
    Dependency-Scan:
        uses: ./.github/workflows/dependency-scan.yml

    Secrets-Scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit
            
    Docker-Scan:
        uses: ./.github/workflows/docker-lint.yml
            
    # Build once the security scans are complete
    Build:
        needs: [Code-Quality, Dependency-Scan, Secrets-Scan, Docker-Scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    Trivy:
        needs: [Build]
        uses: ./.github/workflows/image-scan.yml