name: person

on:
    push: 
        branches: [main]

jobs: 
    
    personal-details:
        runs-on: ubuntu-latest
        steps:
            - name: Printing my name
              run: echo "My name is Harjot Singh."
            - name: Explaining my role
              run: echo "My role is Development Operations Engineer."
            - name: Work Experience
              run: echo "Work Experience - Fresher"
            -